name: Comment ncdump
description: Execute ncdump on all generated datasets and post to comment
inputs:
  token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Install ncdump
      shell: bash
      run: sudo apt-get install -y netcdf-bin
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Get changed files in this PR
      uses: jitterbit/get-changed-files@v1
      id: files
    - name: Run `ncdump -h` on all datasets generated
      shell: bash
      run: |
        find . -name "*.nc" -printf '%p\n' -exec ncdump -h {} \; > "${{ github.workspace }}/ncdumps.txt"
    - name: Annotate PR with ncdumps
      uses: thollander/actions-comment-pull-request@v3
      with:
        github-token: ${{ inputs.token }}
        file-path: "${{ github.workspace }}/ncdumps.txt"
        comment-tag: ncdump
