name: Generate & visualize
on:
  pull_request:
    branches:
      - main

jobs:
  generate-dataset:
    name: Create the dataset(s) to be ingested
    runs-on: ubuntu-latest
    if: github.repository == 'nocollier/test-ci'
    permissions:
      contents: read
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: Get changed files in this PR
        uses: jitterbit/get-changed-files@v1
        id: files
      - name: What is already there?
        run: |
          ls -l
      - name: Run the data generation scripts
        run: |
          uv run python ./scripts/run_generation_scripts.py ${{ steps.files.outputs.all }}
          echo "------------- before"
          cat to_ingest.txt
          echo "------------- after"
      - name: Does it stay?
        run: |
          ls -l
      #- name: Run the ncdump action
      #  uses: ./.github/actions/comment-ncdump
      #  with:
      #    token: ${{ secrets.GHT }}
