name: Publish from Comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  publish-datasets:
    if: >
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/publish') &&
      (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR'
      )
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump Custom Repository/Organization Variables
        env:
          VARS_CONTEXT: ${{ toJson(vars) }}
        run: echo "$VARS_CONTEXT"
      - name: Checkout PR Branch
        uses: actions/checkout@v7
      - name: Verify Clone
        run: |
          git branch
          git log -1
          tree .
      - name: Check user permission
        run: |
          echo "Triggered by an admin/collaborator: ${{ github.event.comment.user.login }}"
      - name: Restore cache
        id: cache-raw-and-artifacts
        uses: actions/cache/restore@v6
        with:
          path: |
            data/*/_raw/*
            data/*/*.nc
            to_ingest.txt
          key: ${{ github.event.number }}-cache
      - name: Add dataset(s) to registry
        run: |
          ls -l
          tree .

      # 3. Commit and push the changes back to the PR
      #- name: Commit and Push Changes
      #  uses: EndBug/add-and-commit@v10
      #  with:
      #    author_name: "Github Actions"
      #    author_email: "41898282+github-actions[bot]@users.noreply.github.com"
      #    message: "publish datasets"
      #    add: "report.txt" # Use '.' to add all changed files
