name: "Regenerate the artifacts"
description: "Runs the submitted convert.py to create artifacts to be ingested."
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'nocollier/test-ci'
    runs-on: ubuntu-latest
    steps: 
      - name: Install uv environment
        uses: astral-sh/setup-uv@v4

      - name: Install ncdump
        run: sudo apt-get install -y netcdf-bin

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get changed files in this PR
        uses: jitterbit/get-changed-files@v1
        id: files

      - name: Set environment variables
        run: |
          echo "DUMP_FILE=${{ github.workspace }}/ncdumps.txt" >> "$GITHUB_ENV"
        
      - name: Generate artifacts & validate
        run: |
          REPO_ROOT=$PWD
          echo "## NetCDF Header Dump of Artifacts" > $DUMP_FILE
          echo "\`\`\`" >> $DUMP_FILE
          for FILE in ${{ steps.files.outputs.all }}; do
            if [ "$(basename "${FILE}")" != "convert.py" ]; then
              continue
            fi
            echo "Running ${FILE}..."
            cd "$(dirname "${FILE}")"
            uv run python convert.py
            for NC_FILE in $(ls *.nc); do
              echo "  Validating ${NC_FILE}..."
              ncdump -h "$NC_FILE" >> $DUMP_FILE
            done
            cd $REPO_ROOT
          done
          echo "\`\`\`" >> $DUMP_FILE
          cat $DUMP_FILE
          
      - name: Annotate PR with ncdumps
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: ${{secrets.GHT}}
          file-path: $DUMP_FILE
          comment-tag: ncdump
          