name: "Regenerate the artifacts"
description: "Runs the submitted convert.py to create artifacts to be ingested."
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'nocollier/test-ci'
    runs-on: ubuntu-latest
    steps: 
      - name: Install uv environment
        uses: astral-sh/setup-uv@v4

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Generate artifacts & validate
        uses: jitterbit/get-changed-files@v1
        id: files
        
      - run: |
          REPO_ROOT=$PWD
          for FILE in ${{ steps.files.outputs.all }}; do
            if [ "$(basename "${FILE}")" -ne "convert.py" ]; then
              continue
            fi
            echo "Running ${FILE}..."
            cd "$(dirname "${FILE}")"
            uv run python convert.py
            for NC_FILE in $(ls *.nc); do
              echo "  Validating ${NC_FILE}..."
            done
            cd $REPO_ROOT
          done
